# Generated by Django 3.2.6 on 2021-08-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210819_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='please input subject', max_length=255),
        ),
    ]
